---
title: "`download_dem()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{`download_dem()`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Description

Digital Elevation Model (DEM) of Australia derived from STRM with 1 Second Grid - Hydrologically Enforced

- Module name: getdata_dem.py
- Bounding Box = Long_min: 112.00, Lat_min: -44.00, Long_max: 154.00, Lat_max: -10.00
- Updates: None
- Resolution: native: 1 arcsec
- Source: https://www.clw.csiro.au/aclep/soilandlandscapegrid/ProductDetails.html
- License: Creative Commons Attribution 4.0 International (CC BY 4.0)
- Attribution: Commonwealth of Australia (Geoscience Australia)

## Layer

- 'DEM_1s'
   - Title: DEM SRTM 1 Second Hydro Enforced
   - Description: The 1 second SRTM derived hydrologically enforced DEM (DEM-H Version 1.0) is a 1 arc second (~30 m) gridded digital elevation model (DEM) that has been hydrologically conditioned and drainage enforced. The DEM-H captures flow paths based on SRTM elevations and mapped stream lines, and supports delineation of catchments and related hydrological attributes.
